# !important
unstable_features = true

# No neat way of sorting these options... 
binop_separator = "Back"
brace_style = "PreferSameLine"
fn_single_line = true
force_multiline_blocks = false
format_code_in_doc_comments = true
group_imports = "StdExternalCrate"
hex_literal_case = "Upper"
imports_granularity = "Item"
indent_style = "Block"
match_block_trailing_comma = true
max_width = 80
merge_derives = false
overflow_delimited_expr = true
trailing_semicolon = false
use_field_init_shorthand = true
use_small_heuristics = "Max"
where_single_line = true
wrap_comments = false
